# Generated by Django 5.2.6 on 2025-10-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
