# Generated by Django 5.2.6 on 2025-11-03 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
