# Generated by Django 5.2.6 on 2025-10-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
    ]
