# Generated by Django 5.2.6 on 2025-10-14 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resume_processed_remove_resume_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
