# Generated by Django 5.2.6 on 2025-10-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
