# Generated by Django 5.2.6 on 2025-10-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_alter_resume_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
    ]
