# Generated by Django 5.2.6 on 2025-11-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_job_remove_resume_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
