# Generated by Django 5.2.6 on 2025-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
